services:
  - type: web
    name: codeatlas-api
    runtime: docker
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: codeatlas-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: GROQ_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://codeatlas-ai.miglanijai2006.chatgpt.site
      - key: CORS_ORIGIN_REGEX
        value: 'https://.*\.vercel\.app'
      - key: REPOSITORY_STORAGE_ROOT
        value: /app/storage/repositories

databases:
  - name: codeatlas-db
    plan: free
    databaseName: codeatlas
    user: codeatlas
